// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYUDyYfRMRce3N8taLlhJO2y90N8QZP30',
    appId: '1:210389489938:web:0720cca5b9c88e18dcfbcb',
    messagingSenderId: '210389489938',
    projectId: 'discipline-bf60e',
    authDomain: 'discipline-bf60e.firebaseapp.com',
    storageBucket: 'discipline-bf60e.firebasestorage.app',
    measurementId: 'G-G0B07VXZ8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5aYiatHR26KBRj8yGdfEpdFlDgqFVZKk',
    appId: '1:210389489938:android:3bc495c91bb55ddedcfbcb',
    messagingSenderId: '210389489938',
    projectId: 'discipline-bf60e',
    storageBucket: 'discipline-bf60e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3QKNweFRTRSZb8EwCr44Buuagq_jGmmo',
    appId: '1:210389489938:ios:985d9ac7cb70472edcfbcb',
    messagingSenderId: '210389489938',
    projectId: 'discipline-bf60e',
    storageBucket: 'discipline-bf60e.firebasestorage.app',
    iosBundleId: 'com.example.discipline',
  );
}
